### ISSUE TITLE
Constants not working for str_replace plugin

### ISSUE THREAD

**Issue by mstrelan** [mstrelan/drudog#4]
PunkAPI uses "kilograms" and "litres" for weights and volumes but the Physical module expects "kg" and "l". We can transform these using the `str_replace` plugin but it's not working with constants.

Example:
```
source:
  constants:
    units_search: ['litres', 'grams', 'kilograms', 'celcius']
    units_replace: ['l', 'g', 'kg', 'c']
process:
  'field_volume/unit':
    plugin: str_replace
    source: volume_unit
    search: constants/units_search
    replace: constants/units_replace
```

For the time being we can hardcode the expected unit to be replaced:
```
process:
  'field_volume/unit':
    plugin: str_replace
    source: volume_unit
    search: litres
    replace: l
```
